com_dir = ../../common/js
com_coffee = ${com_dir}/utils.coffee ${com_dir}/config.coffee ${com_dir}/animation.coffee ${com_dir}/module.coffee ${com_dir}/widget.coffee

all: ${com_coffee} utils.coffee shutdown.coffee confirmdialog.coffee main.coffee
	coffee -cj powerchoose.js $^
