
/*
* THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
*
* This file was generated by the make_dbus.go script.
*/
#ifndef __AUTO_GEN_DBUS_DBUS_greeter
#define __AUTO_GEN_DBUS_DBUS_greeter
#include <glib.h>


gboolean dbus_add_nopwdlogin(char* arg0);

gboolean dbus_remove_nopwdlogin(char* arg0);

#endif