com_dir = ../../common/js
com_coffee = ${com_dir}/utils.coffee ${com_dir}/animation.coffee ${com_dir}/module.coffee ${com_dir}/widget.coffee ${com_dir}/selector.coffee ${com_dir}/plugin.coffee ${com_dir}/menu.coffee

all: ${com_coffee} zone.coffee 
	coffee -cj zone.js $^
