ITEM_WIDTH = 122
ITEM_HEIGHT = 132

SCROLL_STEP_LEN = ITEM_HEIGHT

ALL_APPLICATION_CATEGORY_ID = -1

NUM_SHOWN_ONCE = 10

ITEM_IMG_SIZE = 48

GRID_MARGIN_BOTTOM = 30

ESC_KEY = 27
BACKSPACE_KEY = 8
ENTER_KEY = 13
SPACE_KEY = 32
P_KEY = 112
N_KEY = 110
B_KEY = 98
F_KEY = 102
UP_ARROW = 38
DOWN_ARROW = 40
LEFT_ARROW = 37
RIGHT_ARROW = 39

HIDE_HIDDEN_ICONS = _("Hide hidden icons")
DISPLAY_HIDDEN_ICONS = _("Display hidden icons")

HIDE_ICON = _("Hide this icon")
DISPLAY_ICON = _("Dispaly this icon")
