_b = document.body
_c = $("#container")
grid = $('#grid')
uninstaller = null
searchResult = null
uninstalling_apps = null
isNotForceShow = true
categoryList = null
launcherSetting = null
# startTime = new Date()
