com_dir = ../../../common/js

com_coffee = ${com_dir}/utils.coffee ${com_dir}/animation.coffee ${com_dir}/module.coffee ${com_dir}/widget.coffee ${com_dir}/selector.coffee ${com_dir}/tooltip.coffee
all: ${com_coffee} data.coffee weatherdata.coffee clientcityid.coffee citymoremenu.coffee weather.coffee
	coffee -cj weather.js $^
