#!/usr/bin/env python

lang = ["zh_CN", "zh_TW"]

name = 'weather'

import os

for l in lang:
    os.system('mkdir -p locale/mo/%s/LC_MESSAGES' % l)
    os.system('msgfmt locale/po/%s/%s.po -o locale/mo/%s/LC_MESSAGES/%s.mo' %
            (l, name, l, name))
