#!/usr/bin/env python

lang = ["zh_CN", "zh_TW"]


import os

for l in lang:
    os.system('mkdir -p locale/%s/LC_MESSAGES' % l)
    os.system('msgfmt po/%s/weather.po -o locale/%s/LC_MESSAGES/weather.mo' %
            (l, l))
