#!/usr/bin/python

lang = ["zh_CN", "zh_TW"]


import os
import glob

for l in lang:
    os.system("mkdir -p po/%s" % l)
    os.system("touch po/%s/weather.po" % (l))

    cmd= "xgettext --from-code=utf-8 -L python -j -o po/%s/weather.po %s" % (l,
            " ".join(glob.glob("*.coffee")))
    os.system(cmd)
