com_dir = ../../common/js
com_coffee = ${com_dir}/utils.coffee ${com_dir}/animation.coffee ${com_dir}/module.coffee ${com_dir}/widget.coffee ${com_dir}/selector.coffee
all: ${com_coffee} menu.coffee power.coffee user.coffee time.coffee
	coffee -cj lock.js $^
