com_dir = ../../common/js
weather_dir = weather

all: ${com_dir}/utils.coffee ${weather_dir}/data.coffee ${weather_dir}/weather_url.coffee ${weather_dir}/weather.coffee main.coffee 
	coffee -cj plugins.js $^
