// Generated by CoffeeScript 1.6.2
(function() {
  var DEEPIN_ITEM_ID, Loader, Weather, ajax, allname, assert, build_menu, calc_text_size, cities, clamp, create_element, create_img, dnd_is_deepin_item, dnd_is_desktop, dnd_is_file, echo, find_drag_target, get_function_name, get_page_xy, ip_url1, ip_url2, more_weather_url, now_weather_url, plugins, run_post, swap_element, weather, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Storage.prototype.setObject = function(key, value) {
    return this.setItem(key, JSON.stringify(value));
  };

  Storage.prototype.getObject = function(key) {
    return JSON.parse(this.getItem(key));
  };

  String.prototype.endsWith = function(suffix) {
    return this.indexOf(suffix, this.length - suffix.length) !== -1;
  };

  Array.prototype.remove = function(el) {
    var i;

    i = this.indexOf(el);
    if (i !== -1) {
      return this.splice(this.indexOf(el), 1)[0];
    }
  };

  echo = function(log) {
    return console.log(log);
  };

  assert = function(value, msg) {
    if (!value) {
      throw new Error(msg);
    }
  };

  _ = function(s) {
    return DCore.gettext(s);
  };

  build_menu = function(info) {
    var i, m, sm, v, _i, _len;

    m = new DeepinMenu;
    for (_i = 0, _len = info.length; _i < _len; _i++) {
      v = info[_i];
      if (v.length === 0) {
        i = new DeepinMenuItem(2, 0, 0, 0);
      } else if (typeof v[0] === "number") {
        i = new DeepinMenuItem(0, v[0], v[1], null);
        if (v.length > 2 && v[2] === false) {
          i.enabled = false;
        } else {
          i.enabled = true;
        }
      } else {
        sm = build_menu(v[1]);
        i = new DeepinMenuItem(1, 0, v[0], sm);
      }
      m.appendItem(i);
    }
    return m;
  };

  get_page_xy = function(el, x, y) {
    var p;

    return p = webkitConvertPointFromNodeToPage(el, new WebKitPoint(x, y));
  };

  find_drag_target = function(el) {
    var p;

    p = el;
    if (p.draggable) {
      return p;
    }
    while (p = el.parentNode) {
      if (p.draggable) {
        return p;
      }
    }
    return null;
  };

  swap_element = function(c1, c2) {
    var tmp;

    if (c1.parentNode === c2.parentNode) {
      tmp = document.createElement('div');
      c1.parentNode.insertBefore(tmp, c1);
      c2.parentNode.insertBefore(c1, c2);
      tmp.parentNode.insertBefore(c2, tmp);
      return tmp.parentNode.removeChild(tmp);
    }
  };

  document.body.ondrop = function(e) {
    return e.preventDefault();
  };

  run_post = function(f, self) {
    var f2;

    f2 = f.bind(self || this);
    return setTimeout(f2, 0);
  };

  create_element = function(type, clss, parent) {
    var el;

    el = document.createElement(type);
    if (clss) {
      el.setAttribute("class", clss);
    }
    if (parent) {
      parent.appendChild(el);
    }
    return el;
  };

  create_img = function(clss, src, parent) {
    var el;

    el = create_element('img', clss, parent);
    el.src = src;
    el.draggable = false;
    return el;
  };

  calc_text_size = function(txt, width) {
    var h, tmp;

    tmp = create_element('div', 'hidden_calc_text', document.body);
    tmp.innerText = txt;
    tmp.style.width = "" + width + "px";
    h = tmp.clientHeight;
    document.body.removeChild(tmp);
    return h;
  };

  clamp = function(value, min, max) {
    if (value < min) {
      return min;
    }
    if (value > max) {
      return max;
    }
    return value;
  };

  get_function_name = function() {
    if (!arguments.caller) {
      return "AnymouseFunction";
    }
    return /function (.*?)\(/.exec(arguments.caller.toString())[1];
  };

  DEEPIN_ITEM_ID = "deepin-item-id";

  dnd_is_desktop = function(e) {
    return e.dataTransfer.getData("text/uri-list").trim().endsWith(".desktop");
  };

  dnd_is_deepin_item = function(e) {
    if (e.dataTransfer.getData(DEEPIN_ITEM_ID)) {
      return true;
    } else {
      return false;
    }
  };

  dnd_is_file = function(e) {
    return e.dataTransfer.getData("text/uri-list").length !== 0;
  };

  ajax = function(url, method, callback, asyn) {
    var xhr;

    if (asyn == null) {
      asyn = true;
    }
    xhr = new XMLHttpRequest();
    xhr.open(method, url, asyn);
    xhr.send(null);
    return xhr.onreadystatechange = function() {
      if (xhr.readyState === 4 && xhr.status === 200) {
        return typeof callback === "function" ? callback(xhr) : void 0;
      }
    };
  };

  Loader = (function() {
    function Loader() {
      this._loadsyncjs = __bind(this._loadsyncjs, this);      window.loader = new Object;
      this.loader = window.loader;
      this.syncjs = [];
      this.asyncjs = [];
      this.css = [];
      this.syncjs.has = this.asyncjs.has = this.css.has = function(f) {
        var i, _i, _len;

        for (_i = 0, _len = this.length; _i < _len; _i++) {
          i = this[_i];
          if (f === this[i].src) {
            return true;
          } else {
            return false;
          }
        }
      };
    }

    Loader.prototype.addjs = function(path, sync, callback, args) {
      var js;

      js = null;
      if (sync) {
        js = this.syncjs;
      } else {
        js = this.asyncjs;
      }
      if (!js.has(path)) {
        js.push({
          'src': path,
          'callback': callback,
          'args': args
        });
      }
      return this;
    };

    Loader.prototype.addcss = function(path) {
      if (!this.css.has(path)) {
        this.css.push({
          'src': path
        });
      }
      return this;
    };

    Loader.prototype.load = function() {
      this._loadcss();
      return this._loadsyncjs();
    };

    Loader.prototype._loadcss = function() {
      var ele, head, i, _i, _len, _ref;

      head = document.getElementsByTagName('head')[0];
      _ref = this.css;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        ele = document.createElement('link');
        ele.type = 'text/css';
        ele.rel = 'stylesheet';
        ele.href = i.src;
        head.appendChild(ele);
      }
    };

    Loader.prototype._loadjs = function(object, parent, func) {
      var fs, js;

      fs = [];
      js = document.createElement('script');
      js.type = 'text/javascript';
      if (typeof object.callback === 'function') {
        fs.push(object.callback);
      }
      if (typeof func === 'function') {
        fs.push(func);
      }
      if (fs.length > 0) {
        this._onload(fs, object.args, js);
      }
      js.src = object.src;
      return parent.appendChild(js);
    };

    Loader.prototype._loadsyncjs = function() {
      var head, js;

      if (this.syncjs.length > 0) {
        head = document.getElementsByTagName('head')[0];
        js = this.syncjs.shift();
        return this._loadjs(js, head, this._loadsyncjs);
      } else {
        return this._loadasyncjs();
      }
    };

    Loader.prototype._loadasyncjs = function() {
      var head, i, _i, _len, _ref;

      head = document.getElementsByTagName('head')[0];
      _ref = this.asyncjs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        this._loadjs(asyncjs[i], head);
      }
      return this.asyncjs = [];
    };

    Loader.prototype._onload = function(func, arg, obj) {
      if (obj) {
        if (typeof func === 'function') {
          func = [func];
        }
        if (obj.readyState) {
          obj.onreadystatechange = function() {
            var f, _i, _len, _results;

            if (obj.readyState === 'loaded' || obj.readyState === 'complete') {
              obj.onreadystatechange === null;
              _results = [];
              for (_i = 0, _len = func.length; _i < _len; _i++) {
                f = func[_i];
                _results.push(f(arg));
              }
              return _results;
            }
          };
        } else {
          obj.onload = function() {
            var f, _i, _len, _results;

            _results = [];
            for (_i = 0, _len = func.length; _i < _len; _i++) {
              f = func[_i];
              _results.push(f(arg));
            }
            return _results;
          };
        }
      }
    };

    return Loader;

  })();

  cities = [
    {
      "id": "01",
      "name": "北京"
    }, {
      "id": "02",
      "name": "上海"
    }, {
      "id": "03",
      "name": "天津"
    }, {
      "id": "04",
      "name": "重庆"
    }, {
      "id": "05",
      "name": "黑龙江"
    }, {
      "id": "06",
      "name": "吉林"
    }, {
      "id": "07",
      "name": "辽宁"
    }, {
      "id": "08",
      "name": "内蒙古"
    }, {
      "id": "09",
      "name": "河北"
    }, {
      "id": "10",
      "name": "山西"
    }, {
      "id": "11",
      "name": "陕西"
    }, {
      "id": "12",
      "name": "山东"
    }, {
      "id": "13",
      "name": "新疆"
    }, {
      "id": "14",
      "name": "西藏"
    }, {
      "id": "15",
      "name": "青海"
    }, {
      "id": "16",
      "name": "甘肃"
    }, {
      "id": "17",
      "name": "宁夏"
    }, {
      "id": "18",
      "name": "河南"
    }, {
      "id": "19",
      "name": "江苏"
    }, {
      "id": "20",
      "name": "湖北"
    }, {
      "id": "21",
      "name": "浙江"
    }, {
      "id": "22",
      "name": "安徽"
    }, {
      "id": "23",
      "name": "福建"
    }, {
      "id": "24",
      "name": "江西"
    }, {
      "id": "25",
      "name": "湖南"
    }, {
      "id": "26",
      "name": "贵州"
    }, {
      "id": "27",
      "name": "四川"
    }, {
      "id": "28",
      "name": "广东"
    }, {
      "id": "29",
      "name": "云南"
    }, {
      "id": "30",
      "name": "广西"
    }, {
      "id": "31",
      "name": "海南"
    }, {
      "id": "32",
      "name": "香港"
    }, {
      "id": "33",
      "name": "澳门"
    }, {
      "id": "34",
      "name": "台湾"
    }
  ];

  allname = {
    "data": [
      {
        "prov": "澳门",
        "city": [
          {
            "cityname": "澳门",
            "code": "101330101"
          }
        ]
      }, {
        "prov": "香港",
        "city": [
          {
            "cityname": "香港",
            "code": "101320101"
          }
        ]
      }, {
        "prov": "台湾",
        "city": [
          {
            "cityname": "台北",
            "code": "101340102"
          }, {
            "cityname": "高雄",
            "code": "101340201"
          }
        ]
      }, {
        "prov": "北京",
        "city": [
          {
            "cityname": "北京",
            "code": "101010100"
          }, {
            "cityname": "朝阳",
            "code": "101010300"
          }, {
            "cityname": "顺义",
            "code": "101010400"
          }, {
            "cityname": "怀柔",
            "code": "101010500"
          }, {
            "cityname": "通州",
            "code": "101010600"
          }, {
            "cityname": "昌平",
            "code": "101010700"
          }, {
            "cityname": "延庆",
            "code": "101010800"
          }, {
            "cityname": "丰台",
            "code": "101010900"
          }, {
            "cityname": "石景山",
            "code": "101011000"
          }, {
            "cityname": "大兴",
            "code": "101011100"
          }, {
            "cityname": "房山",
            "code": "101011200"
          }, {
            "cityname": "密云",
            "code": "101011300"
          }, {
            "cityname": "门头沟",
            "code": "101011400"
          }, {
            "cityname": "平谷",
            "code": "101011500"
          }, {
            "cityname": "八达岭",
            "code": "101011600"
          }, {
            "cityname": "佛爷顶",
            "code": "101011700"
          }, {
            "cityname": "汤河口",
            "code": "101011800"
          }, {
            "cityname": "密云上甸子",
            "code": "101011900"
          }, {
            "cityname": "斋堂",
            "code": "101012000"
          }, {
            "cityname": "霞云岭",
            "code": "101012100"
          }, {
            "cityname": "北京城区",
            "code": "101012200"
          }, {
            "cityname": "海淀",
            "code": "101010200"
          }
        ]
      }, {
        "prov": "天津",
        "city": [
          {
            "cityname": "天津",
            "code": "101030100"
          }, {
            "cityname": "宝坻",
            "code": "101030300"
          }, {
            "cityname": "东丽",
            "code": "101030400"
          }, {
            "cityname": "西青",
            "code": "101030500"
          }, {
            "cityname": "北辰",
            "code": "101030600"
          }, {
            "cityname": "蓟县",
            "code": "101031400"
          }, {
            "cityname": "汉沽",
            "code": "101030800"
          }, {
            "cityname": "静海",
            "code": "101030900"
          }, {
            "cityname": "津南",
            "code": "101031000"
          }, {
            "cityname": "塘沽",
            "code": "101031100"
          }, {
            "cityname": "大港",
            "code": "101031200"
          }, {
            "cityname": "武清",
            "code": "101030200"
          }, {
            "cityname": "宁河",
            "code": "101030700"
          }
        ]
      }, {
        "prov": "上海",
        "city": [
          {
            "cityname": "上海",
            "code": "101020100"
          }, {
            "cityname": "宝山",
            "code": "101020300"
          }, {
            "cityname": "嘉定",
            "code": "101020500"
          }, {
            "cityname": "南汇",
            "code": "101020600"
          }, {
            "cityname": "浦东",
            "code": "101021300"
          }, {
            "cityname": "青浦",
            "code": "101020800"
          }, {
            "cityname": "松江",
            "code": "101020900"
          }, {
            "cityname": "奉贤",
            "code": "101021000"
          }, {
            "cityname": "崇明",
            "code": "101021100"
          }, {
            "cityname": "徐家汇",
            "code": "101021200"
          }, {
            "cityname": "闵行",
            "code": "101020200"
          }, {
            "cityname": "金山",
            "code": "101020700"
          }
        ]
      }, {
        "prov": "河北",
        "city": [
          {
            "cityname": "石家庄",
            "code": "101090101"
          }, {
            "cityname": "张家口",
            "code": "101090301"
          }, {
            "cityname": "承德",
            "code": "101090402"
          }, {
            "cityname": "唐山",
            "code": "101090501"
          }, {
            "cityname": "秦皇岛",
            "code": "101091101"
          }, {
            "cityname": "沧州",
            "code": "101090701"
          }, {
            "cityname": "衡水",
            "code": "101090801"
          }, {
            "cityname": "邢台",
            "code": "101090901"
          }, {
            "cityname": "邯郸",
            "code": "101091001"
          }, {
            "cityname": "保定",
            "code": "101090201"
          }, {
            "cityname": "廊坊",
            "code": "101090601"
          }
        ]
      }, {
        "prov": "河南",
        "city": [
          {
            "cityname": "郑州",
            "code": "101180101"
          }, {
            "cityname": "新乡",
            "code": "101180301"
          }, {
            "cityname": "许昌",
            "code": "101180401"
          }, {
            "cityname": "平顶山",
            "code": "101180501"
          }, {
            "cityname": "信阳",
            "code": "101180601"
          }, {
            "cityname": "南阳",
            "code": "101180701"
          }, {
            "cityname": "开封",
            "code": "101180801"
          }, {
            "cityname": "洛阳",
            "code": "101180901"
          }, {
            "cityname": "商丘",
            "code": "101181001"
          }, {
            "cityname": "焦作",
            "code": "101181101"
          }, {
            "cityname": "鹤壁",
            "code": "101181201"
          }, {
            "cityname": "濮阳",
            "code": "101181301"
          }, {
            "cityname": "周口",
            "code": "101181401"
          }, {
            "cityname": "漯河",
            "code": "101181501"
          }, {
            "cityname": "驻马店",
            "code": "101181601"
          }, {
            "cityname": "三门峡",
            "code": "101181701"
          }, {
            "cityname": "济源",
            "code": "101181801"
          }, {
            "cityname": "安阳",
            "code": "101180201"
          }
        ]
      }, {
        "prov": "安徽",
        "city": [
          {
            "cityname": "合肥",
            "code": "101220101"
          }, {
            "cityname": "芜湖",
            "code": "101220301"
          }, {
            "cityname": "淮南",
            "code": "101220401"
          }, {
            "cityname": "马鞍山",
            "code": "101220501"
          }, {
            "cityname": "安庆",
            "code": "101220601"
          }, {
            "cityname": "宿州",
            "code": "101220701"
          }, {
            "cityname": "阜阳",
            "code": "101220801"
          }, {
            "cityname": "亳州",
            "code": "101220901"
          }, {
            "cityname": "黄山",
            "code": "101221001"
          }, {
            "cityname": "滁州",
            "code": "101221101"
          }, {
            "cityname": "淮北",
            "code": "101221201"
          }, {
            "cityname": "铜陵",
            "code": "101221301"
          }, {
            "cityname": "宣城",
            "code": "101221401"
          }, {
            "cityname": "六安",
            "code": "101221501"
          }, {
            "cityname": "巢湖",
            "code": "101221601"
          }, {
            "cityname": "池州",
            "code": "101221701"
          }, {
            "cityname": "蚌埠",
            "code": "101220201"
          }
        ]
      }, {
        "prov": "浙江",
        "city": [
          {
            "cityname": "杭州",
            "code": "101210101"
          }, {
            "cityname": "舟山",
            "code": "101211101"
          }, {
            "cityname": "湖州",
            "code": "101210201"
          }, {
            "cityname": "嘉兴",
            "code": "101210301"
          }, {
            "cityname": "金华",
            "code": "101210901"
          }, {
            "cityname": "绍兴",
            "code": "101210501"
          }, {
            "cityname": "台州",
            "code": "101210601"
          }, {
            "cityname": "温州",
            "code": "101210701"
          }, {
            "cityname": "丽水",
            "code": "101210801"
          }, {
            "cityname": "衢州",
            "code": "101211001"
          }, {
            "cityname": "宁波",
            "code": "101210401"
          }
        ]
      }, {
        "prov": "重庆",
        "city": [
          {
            "cityname": "重庆",
            "code": "101040100"
          }, {
            "cityname": "合川",
            "code": "101040300"
          }, {
            "cityname": "南川",
            "code": "101040400"
          }, {
            "cityname": "江津",
            "code": "101040500"
          }, {
            "cityname": "万盛",
            "code": "101040600"
          }, {
            "cityname": "渝北",
            "code": "101040700"
          }, {
            "cityname": "北碚",
            "code": "101040800"
          }, {
            "cityname": "巴南",
            "code": "101040900"
          }, {
            "cityname": "长寿",
            "code": "101041000"
          }, {
            "cityname": "黔江",
            "code": "101041100"
          }, {
            "cityname": "万州天城",
            "code": "101041200"
          }, {
            "cityname": "万州龙宝",
            "code": "101041300"
          }, {
            "cityname": "涪陵",
            "code": "101041400"
          }, {
            "cityname": "开县",
            "code": "101041500"
          }, {
            "cityname": "城口",
            "code": "101041600"
          }, {
            "cityname": "云阳",
            "code": "101041700"
          }, {
            "cityname": "巫溪",
            "code": "101041800"
          }, {
            "cityname": "奉节",
            "code": "101041900"
          }, {
            "cityname": "巫山",
            "code": "101042000"
          }, {
            "cityname": "潼南",
            "code": "101042100"
          }, {
            "cityname": "垫江",
            "code": "101042200"
          }, {
            "cityname": "梁平",
            "code": "101042300"
          }, {
            "cityname": "忠县",
            "code": "101042400"
          }, {
            "cityname": "石柱",
            "code": "101042500"
          }, {
            "cityname": "大足",
            "code": "101042600"
          }, {
            "cityname": "荣昌",
            "code": "101042700"
          }, {
            "cityname": "铜梁",
            "code": "101042800"
          }, {
            "cityname": "璧山",
            "code": "101042900"
          }, {
            "cityname": "丰都",
            "code": "101043000"
          }, {
            "cityname": "武隆",
            "code": "101043100"
          }, {
            "cityname": "彭水",
            "code": "101043200"
          }, {
            "cityname": "綦江",
            "code": "101043300"
          }, {
            "cityname": "酉阳",
            "code": "101043400"
          }, {
            "cityname": "秀山",
            "code": "101043600"
          }, {
            "cityname": "沙坪坝",
            "code": "101043700"
          }, {
            "cityname": "永川",
            "code": "101040200"
          }
        ]
      }, {
        "prov": "福建",
        "city": [
          {
            "cityname": "福州",
            "code": "101230101"
          }, {
            "cityname": "泉州",
            "code": "101230501"
          }, {
            "cityname": "漳州",
            "code": "101230601"
          }, {
            "cityname": "龙岩",
            "code": "101230701"
          }, {
            "cityname": "晋江",
            "code": "101230509"
          }, {
            "cityname": "南平",
            "code": "101230901"
          }, {
            "cityname": "厦门",
            "code": "101230201"
          }, {
            "cityname": "宁德",
            "code": "101230301"
          }, {
            "cityname": "莆田",
            "code": "101230401"
          }, {
            "cityname": "三明",
            "code": "101230801"
          }
        ]
      }, {
        "prov": "甘肃",
        "city": [
          {
            "cityname": "兰州",
            "code": "101160101"
          }, {
            "cityname": "平凉",
            "code": "101160301"
          }, {
            "cityname": "庆阳",
            "code": "101160401"
          }, {
            "cityname": "武威",
            "code": "101160501"
          }, {
            "cityname": "金昌",
            "code": "101160601"
          }, {
            "cityname": "嘉峪关",
            "code": "101161401"
          }, {
            "cityname": "酒泉",
            "code": "101160801"
          }, {
            "cityname": "天水",
            "code": "101160901"
          }, {
            "cityname": "武都",
            "code": "101161001"
          }, {
            "cityname": "临夏",
            "code": "101161101"
          }, {
            "cityname": "合作",
            "code": "101161201"
          }, {
            "cityname": "白银",
            "code": "101161301"
          }, {
            "cityname": "定西",
            "code": "101160201"
          }, {
            "cityname": "张掖",
            "code": "101160701"
          }
        ]
      }, {
        "prov": "广东",
        "city": [
          {
            "cityname": "广州",
            "code": "101280101"
          }, {
            "cityname": "惠州",
            "code": "101280301"
          }, {
            "cityname": "梅州",
            "code": "101280401"
          }, {
            "cityname": "汕头",
            "code": "101280501"
          }, {
            "cityname": "深圳",
            "code": "101280601"
          }, {
            "cityname": "珠海",
            "code": "101280701"
          }, {
            "cityname": "佛山",
            "code": "101280800"
          }, {
            "cityname": "肇庆",
            "code": "101280901"
          }, {
            "cityname": "湛江",
            "code": "101281001"
          }, {
            "cityname": "江门",
            "code": "101281101"
          }, {
            "cityname": "河源",
            "code": "101281201"
          }, {
            "cityname": "清远",
            "code": "101281301"
          }, {
            "cityname": "云浮",
            "code": "101281401"
          }, {
            "cityname": "潮州",
            "code": "101281501"
          }, {
            "cityname": "东莞",
            "code": "101281601"
          }, {
            "cityname": "中山",
            "code": "101281701"
          }, {
            "cityname": "阳江",
            "code": "101281801"
          }, {
            "cityname": "揭阳",
            "code": "101281901"
          }, {
            "cityname": "茂名",
            "code": "101282001"
          }, {
            "cityname": "汕尾",
            "code": "101282101"
          }, {
            "cityname": "韶关",
            "code": "101280201"
          }
        ]
      }, {
        "prov": "广西",
        "city": [
          {
            "cityname": "南宁",
            "code": "101300101"
          }, {
            "cityname": "柳州",
            "code": "101300301"
          }, {
            "cityname": "来宾",
            "code": "101300401"
          }, {
            "cityname": "桂林",
            "code": "101300501"
          }, {
            "cityname": "梧州",
            "code": "101300601"
          }, {
            "cityname": "防城港",
            "code": "101301401"
          }, {
            "cityname": "贵港",
            "code": "101300801"
          }, {
            "cityname": "玉林",
            "code": "101300901"
          }, {
            "cityname": "百色",
            "code": "101301001"
          }, {
            "cityname": "钦州",
            "code": "101301101"
          }, {
            "cityname": "河池",
            "code": "101301201"
          }, {
            "cityname": "北海",
            "code": "101301301"
          }, {
            "cityname": "崇左",
            "code": "101300201"
          }, {
            "cityname": "贺州",
            "code": "101300701"
          }
        ]
      }, {
        "prov": "贵州",
        "city": [
          {
            "cityname": "贵阳",
            "code": "101260101"
          }, {
            "cityname": "安顺",
            "code": "101260301"
          }, {
            "cityname": "都匀",
            "code": "101260401"
          }, {
            "cityname": "兴义",
            "code": "101260906"
          }, {
            "cityname": "铜仁",
            "code": "101260601"
          }, {
            "cityname": "毕节",
            "code": "101260701"
          }, {
            "cityname": "六盘水",
            "code": "101260801"
          }, {
            "cityname": "遵义",
            "code": "101260201"
          }, {
            "cityname": "凯里",
            "code": "101260501"
          }
        ]
      }, {
        "prov": "云南",
        "city": [
          {
            "cityname": "昆明",
            "code": "101290101"
          }, {
            "cityname": "红河",
            "code": "101290301"
          }, {
            "cityname": "文山",
            "code": "101290601"
          }, {
            "cityname": "玉溪",
            "code": "101290701"
          }, {
            "cityname": "楚雄",
            "code": "101290801"
          }, {
            "cityname": "普洱",
            "code": "101290901"
          }, {
            "cityname": "昭通",
            "code": "101291001"
          }, {
            "cityname": "临沧",
            "code": "101291101"
          }, {
            "cityname": "怒江",
            "code": "101291201"
          }, {
            "cityname": "香格里拉",
            "code": "101291301"
          }, {
            "cityname": "丽江",
            "code": "101291401"
          }, {
            "cityname": "德宏",
            "code": "101291501"
          }, {
            "cityname": "景洪",
            "code": "101291601"
          }, {
            "cityname": "大理",
            "code": "101290201"
          }, {
            "cityname": "曲靖",
            "code": "101290401"
          }, {
            "cityname": "保山",
            "code": "101290501"
          }
        ]
      }, {
        "prov": "内蒙古",
        "city": [
          {
            "cityname": "呼和浩特",
            "code": "101080101"
          }, {
            "cityname": "乌海",
            "code": "101080301"
          }, {
            "cityname": "集宁",
            "code": "101080401"
          }, {
            "cityname": "通辽",
            "code": "101080501"
          }, {
            "cityname": "阿拉善左旗",
            "code": "101081201"
          }, {
            "cityname": "鄂尔多斯",
            "code": "101080701"
          }, {
            "cityname": "临河",
            "code": "101080801"
          }, {
            "cityname": "锡林浩特",
            "code": "101080901"
          }, {
            "cityname": "呼伦贝尔",
            "code": "101081000"
          }, {
            "cityname": "乌兰浩特",
            "code": "101081101"
          }, {
            "cityname": "包头",
            "code": "101080201"
          }, {
            "cityname": "赤峰",
            "code": "101080601"
          }
        ]
      }, {
        "prov": "江西",
        "city": [
          {
            "cityname": "南昌",
            "code": "101240101"
          }, {
            "cityname": "上饶",
            "code": "101240301"
          }, {
            "cityname": "抚州",
            "code": "101240401"
          }, {
            "cityname": "宜春",
            "code": "101240501"
          }, {
            "cityname": "鹰潭",
            "code": "101241101"
          }, {
            "cityname": "赣州",
            "code": "101240701"
          }, {
            "cityname": "景德镇",
            "code": "101240801"
          }, {
            "cityname": "萍乡",
            "code": "101240901"
          }, {
            "cityname": "新余",
            "code": "101241001"
          }, {
            "cityname": "九江",
            "code": "101240201"
          }, {
            "cityname": "吉安",
            "code": "101240601"
          }
        ]
      }, {
        "prov": "湖北",
        "city": [
          {
            "cityname": "武汉",
            "code": "101200101"
          }, {
            "cityname": "黄冈",
            "code": "101200501"
          }, {
            "cityname": "荆州",
            "code": "101200801"
          }, {
            "cityname": "宜昌",
            "code": "101200901"
          }, {
            "cityname": "恩施",
            "code": "101201001"
          }, {
            "cityname": "十堰",
            "code": "101201101"
          }, {
            "cityname": "神农架",
            "code": "101201201"
          }, {
            "cityname": "随州",
            "code": "101201301"
          }, {
            "cityname": "荆门",
            "code": "101201401"
          }, {
            "cityname": "天门",
            "code": "101201501"
          }, {
            "cityname": "仙桃",
            "code": "101201601"
          }, {
            "cityname": "潜江",
            "code": "101201701"
          }, {
            "cityname": "襄樊",
            "code": "101200201"
          }, {
            "cityname": "鄂州",
            "code": "101200301"
          }, {
            "cityname": "孝感",
            "code": "101200401"
          }, {
            "cityname": "黄石",
            "code": "101200601"
          }, {
            "cityname": "咸宁",
            "code": "101200701"
          }
        ]
      }, {
        "prov": "四川",
        "city": [
          {
            "cityname": "成都",
            "code": "101270101"
          }, {
            "cityname": "自贡",
            "code": "101270301"
          }, {
            "cityname": "绵阳",
            "code": "101270401"
          }, {
            "cityname": "南充",
            "code": "101270501"
          }, {
            "cityname": "达州",
            "code": "101270601"
          }, {
            "cityname": "遂宁",
            "code": "101270701"
          }, {
            "cityname": "广安",
            "code": "101270801"
          }, {
            "cityname": "巴中",
            "code": "101270901"
          }, {
            "cityname": "泸州",
            "code": "101271001"
          }, {
            "cityname": "宜宾",
            "code": "101271101"
          }, {
            "cityname": "内江",
            "code": "101271201"
          }, {
            "cityname": "资阳",
            "code": "101271301"
          }, {
            "cityname": "乐山",
            "code": "101271401"
          }, {
            "cityname": "眉山",
            "code": "101271501"
          }, {
            "cityname": "凉山",
            "code": "101271601"
          }, {
            "cityname": "雅安",
            "code": "101271701"
          }, {
            "cityname": "甘孜",
            "code": "101271801"
          }, {
            "cityname": "阿坝",
            "code": "101271901"
          }, {
            "cityname": "德阳",
            "code": "101272001"
          }, {
            "cityname": "广元",
            "code": "101272101"
          }, {
            "cityname": "攀枝花",
            "code": "101270201"
          }
        ]
      }, {
        "prov": "宁夏",
        "city": [
          {
            "cityname": "银川",
            "code": "101170101"
          }, {
            "cityname": "中卫",
            "code": "101170501"
          }, {
            "cityname": "固原",
            "code": "101170401"
          }, {
            "cityname": "石嘴山",
            "code": "101170201"
          }, {
            "cityname": "吴忠",
            "code": "101170301"
          }
        ]
      }, {
        "prov": "青海prov",
        "city": [
          {
            "cityname": "西宁",
            "code": "101150101"
          }, {
            "cityname": "黄南",
            "code": "101150301"
          }, {
            "cityname": "海北",
            "code": "101150801"
          }, {
            "cityname": "果洛",
            "code": "101150501"
          }, {
            "cityname": "玉树",
            "code": "101150601"
          }, {
            "cityname": "海西",
            "code": "101150701"
          }, {
            "cityname": "海东",
            "code": "101150201"
          }, {
            "cityname": "海南",
            "code": "101150401"
          }
        ]
      }, {
        "prov": "山东",
        "city": [
          {
            "cityname": "济南",
            "code": "101120101"
          }, {
            "cityname": "潍坊",
            "code": "101120601"
          }, {
            "cityname": "临沂",
            "code": "101120901"
          }, {
            "cityname": "菏泽",
            "code": "101121001"
          }, {
            "cityname": "滨州",
            "code": "101121101"
          }, {
            "cityname": "东营",
            "code": "101121201"
          }, {
            "cityname": "威海",
            "code": "101121301"
          }, {
            "cityname": "枣庄",
            "code": "101121401"
          }, {
            "cityname": "日照",
            "code": "101121501"
          }, {
            "cityname": "莱芜",
            "code": "101121601"
          }, {
            "cityname": "聊城",
            "code": "101121701"
          }, {
            "cityname": "青岛",
            "code": "101120201"
          }, {
            "cityname": "淄博",
            "code": "101120301"
          }, {
            "cityname": "德州",
            "code": "101120401"
          }, {
            "cityname": "烟台",
            "code": "101120501"
          }, {
            "cityname": "济宁",
            "code": "101120701"
          }, {
            "cityname": "泰安",
            "code": "101120801"
          }
        ]
      }, {
        "prov": "陕西prov",
        "city": [
          {
            "cityname": "西安",
            "code": "101110101"
          }, {
            "cityname": "延安",
            "code": "101110300"
          }, {
            "cityname": "榆林",
            "code": "101110401"
          }, {
            "cityname": "铜川",
            "code": "101111001"
          }, {
            "cityname": "商洛",
            "code": "101110601"
          }, {
            "cityname": "安康",
            "code": "101110701"
          }, {
            "cityname": "汉中",
            "code": "101110801"
          }, {
            "cityname": "宝鸡",
            "code": "101110901"
          }, {
            "cityname": "咸阳",
            "code": "101110200"
          }, {
            "cityname": "渭南",
            "code": "101110501"
          }
        ]
      }, {
        "prov": "山西",
        "city": [
          {
            "cityname": "太原",
            "code": "101100101"
          }, {
            "cityname": "临汾",
            "code": "101100701"
          }, {
            "cityname": "运城",
            "code": "101100801"
          }, {
            "cityname": "朔州",
            "code": "101100901"
          }, {
            "cityname": "忻州",
            "code": "101101001"
          }, {
            "cityname": "长治",
            "code": "101100501"
          }, {
            "cityname": "大同",
            "code": "101100201"
          }, {
            "cityname": "阳泉",
            "code": "101100301"
          }, {
            "cityname": "晋中",
            "code": "101100401"
          }, {
            "cityname": "晋城",
            "code": "101100601"
          }, {
            "cityname": "吕梁",
            "code": "101101100"
          }
        ]
      }, {
        "prov": "新疆",
        "city": [
          {
            "cityname": "乌鲁木齐",
            "code": "101130101"
          }, {
            "cityname": "石河子",
            "code": "101130301"
          }, {
            "cityname": "昌吉",
            "code": "101130401"
          }, {
            "cityname": "吐鲁番",
            "code": "101130501"
          }, {
            "cityname": "库尔勒",
            "code": "101130601"
          }, {
            "cityname": "阿拉尔",
            "code": "101130701"
          }, {
            "cityname": "阿克苏",
            "code": "101130801"
          }, {
            "cityname": "喀什",
            "code": "101130901"
          }, {
            "cityname": "伊宁",
            "code": "101131001"
          }, {
            "cityname": "塔城",
            "code": "101131101"
          }, {
            "cityname": "哈密",
            "code": "101131201"
          }, {
            "cityname": "和田",
            "code": "101131301"
          }, {
            "cityname": "阿勒泰",
            "code": "101131401"
          }, {
            "cityname": "阿图什",
            "code": "101131501"
          }, {
            "cityname": "博乐",
            "code": "101131601"
          }, {
            "cityname": "克拉玛依",
            "code": "101130201"
          }
        ]
      }, {
        "prov": "西藏",
        "city": [
          {
            "cityname": "拉萨",
            "code": "101140101"
          }, {
            "cityname": "山南",
            "code": "101140301"
          }, {
            "cityname": "阿里",
            "code": "101140701"
          }, {
            "cityname": "昌都",
            "code": "101140501"
          }, {
            "cityname": "那曲",
            "code": "101140601"
          }, {
            "cityname": "日喀则",
            "code": "101140201"
          }, {
            "cityname": "林芝",
            "code": "101140401"
          }
        ]
      }, {
        "prov": "台湾",
        "city": [
          {
            "cityname": "台北县",
            "code": "101340101"
          }, {
            "cityname": "高雄",
            "code": "101340201"
          }, {
            "cityname": "台中",
            "code": "101340401"
          }
        ]
      }, {
        "prov": "海南prov",
        "city": [
          {
            "cityname": "海口",
            "code": "101310101"
          }, {
            "cityname": "三亚",
            "code": "101310201"
          }, {
            "cityname": "东方",
            "code": "101310202"
          }, {
            "cityname": "临高",
            "code": "101310203"
          }, {
            "cityname": "澄迈",
            "code": "101310204"
          }, {
            "cityname": "儋州",
            "code": "101310205"
          }, {
            "cityname": "昌江",
            "code": "101310206"
          }, {
            "cityname": "白沙",
            "code": "101310207"
          }, {
            "cityname": "琼中",
            "code": "101310208"
          }, {
            "cityname": "定安",
            "code": "101310209"
          }, {
            "cityname": "屯昌",
            "code": "101310210"
          }, {
            "cityname": "琼海",
            "code": "101310211"
          }, {
            "cityname": "文昌",
            "code": "101310212"
          }, {
            "cityname": "保亭",
            "code": "101310214"
          }, {
            "cityname": "万宁",
            "code": "101310215"
          }, {
            "cityname": "陵水",
            "code": "101310216"
          }, {
            "cityname": "西沙",
            "code": "101310217"
          }, {
            "cityname": "南沙岛",
            "code": "101310220"
          }, {
            "cityname": "乐东",
            "code": "101310221"
          }, {
            "cityname": "五指山",
            "code": "101310222"
          }, {
            "cityname": "琼山",
            "code": "101310102"
          }
        ]
      }, {
        "prov": "湖南",
        "city": [
          {
            "cityname": "长沙",
            "code": "101250101"
          }, {
            "cityname": "株洲",
            "code": "101250301"
          }, {
            "cityname": "衡阳",
            "code": "101250401"
          }, {
            "cityname": "郴州",
            "code": "101250501"
          }, {
            "cityname": "常德",
            "code": "101250601"
          }, {
            "cityname": "益阳",
            "code": "101250700"
          }, {
            "cityname": "娄底",
            "code": "101250801"
          }, {
            "cityname": "邵阳",
            "code": "101250901"
          }, {
            "cityname": "岳阳",
            "code": "101251001"
          }, {
            "cityname": "张家界",
            "code": "101251101"
          }, {
            "cityname": "怀化",
            "code": "101251201"
          }, {
            "cityname": "黔阳",
            "code": "101251301"
          }, {
            "cityname": "永州",
            "code": "101251401"
          }, {
            "cityname": "吉首",
            "code": "101251501"
          }, {
            "cityname": "湘潭",
            "code": "101250201"
          }
        ]
      }, {
        "prov": "江苏",
        "city": [
          {
            "cityname": "南京",
            "code": "101190101"
          }, {
            "cityname": "镇江",
            "code": "101190301"
          }, {
            "cityname": "苏州",
            "code": "101190401"
          }, {
            "cityname": "南通",
            "code": "101190501"
          }, {
            "cityname": "扬州",
            "code": "101190601"
          }, {
            "cityname": "宿迁",
            "code": "101191301"
          }, {
            "cityname": "徐州",
            "code": "101190801"
          }, {
            "cityname": "淮安",
            "code": "101190901"
          }, {
            "cityname": "连云港",
            "code": "101191001"
          }, {
            "cityname": "常州",
            "code": "101191101"
          }, {
            "cityname": "泰州",
            "code": "101191201"
          }, {
            "cityname": "无锡",
            "code": "101190201"
          }, {
            "cityname": "盐城",
            "code": "101190701"
          }
        ]
      }, {
        "prov": "黑龙江",
        "city": [
          {
            "cityname": "哈尔滨",
            "code": "101050101"
          }, {
            "cityname": "牡丹江",
            "code": "101050301"
          }, {
            "cityname": "佳木斯",
            "code": "101050401"
          }, {
            "cityname": "绥化",
            "code": "101050501"
          }, {
            "cityname": "黑河",
            "code": "101050601"
          }, {
            "cityname": "双鸭山",
            "code": "101051301"
          }, {
            "cityname": "伊春",
            "code": "101050801"
          }, {
            "cityname": "大庆",
            "code": "101050901"
          }, {
            "cityname": "七台河",
            "code": "101051002"
          }, {
            "cityname": "鸡西",
            "code": "101051101"
          }, {
            "cityname": "鹤岗",
            "code": "101051201"
          }, {
            "cityname": "齐齐哈尔",
            "code": "101050201"
          }, {
            "cityname": "大兴安岭",
            "code": "101050701"
          }
        ]
      }, {
        "prov": "吉林",
        "city": [
          {
            "cityname": "长春",
            "code": "101060101"
          }, {
            "cityname": "延吉",
            "code": "101060301"
          }, {
            "cityname": "四平",
            "code": "101060401"
          }, {
            "cityname": "白山",
            "code": "101060901"
          }, {
            "cityname": "白城",
            "code": "101060601"
          }, {
            "cityname": "辽源",
            "code": "101060701"
          }, {
            "cityname": "松原",
            "code": "101060801"
          }, {
            "cityname": "吉林",
            "code": "101060201"
          }, {
            "cityname": "通化",
            "code": "101060501"
          }
        ]
      }, {
        "prov": "辽宁",
        "city": [
          {
            "cityname": "沈阳",
            "code": "101070101"
          }, {
            "cityname": "鞍山",
            "code": "101070301"
          }, {
            "cityname": "抚顺",
            "code": "101070401"
          }, {
            "cityname": "本溪",
            "code": "101070501"
          }, {
            "cityname": "丹东",
            "code": "101070601"
          }, {
            "cityname": "葫芦岛",
            "code": "101071401"
          }, {
            "cityname": "营口",
            "code": "101070801"
          }, {
            "cityname": "阜新",
            "code": "101070901"
          }, {
            "cityname": "辽阳",
            "code": "101071001"
          }, {
            "cityname": "铁岭",
            "code": "101071101"
          }, {
            "cityname": "朝阳",
            "code": "101071201"
          }, {
            "cityname": "盘锦",
            "code": "101071301"
          }, {
            "cityname": "大连",
            "code": "101070201"
          }, {
            "cityname": "锦州",
            "code": "101070701"
          }
        ]
      }
    ]
  };

  ip_url1 = function() {
    return "http://int.dpool.sina.com.cn/iplookup/iplookup.php";
  };

  ip_url2 = function(ip) {
    return "http://int.dpool.sina.com.cn/iplookup/iplookup.php?format=js&ip=" + ip;
  };

  now_weather_url = function(cityid) {
    return "http://www.weather.com.cn/data/sk/" + cityid + ".html";
  };

  more_weather_url = function(cityid) {
    return "http://m.weather.com.cn/data/" + cityid + ".html";
  };

  Weather = (function() {
    function Weather() {
      this.id = "weather";
      this.pos = {
        x: 10,
        y: 1,
        width: 3,
        height: 1
      };
      this.element = document.createElement('div');
      this.element.setAttribute('class', "Weather");
      this.element.draggable = true;
      this.weathergui_init();
    }

    Weather.prototype.get_id = function() {
      return this.id;
    };

    Weather.prototype.set_id = function(id) {
      return this.id = id;
    };

    Weather.prototype.get_pos = function() {
      return this.pos;
    };

    Weather.prototype.set_pos = function(pos) {
      return this.pos = pos;
    };

    Weather.prototype.weather_style_build = function() {
      var city_and_date, img_now_url_init, left_div, right_div, temperature_now,
        _this = this;

      this.img_url_first = "desktop_plugin/weather/img/";
      img_now_url_init = this.img_url_first + "48/T" + "0\u6674" + ".png";
      left_div = create_element("div", "left_div", this.element);
      this.weather_now_pic = create_img("weather_now_pic", img_now_url_init, left_div);
      right_div = create_element("div", "right_div", this.element);
      temperature_now = create_element("div", "temperature_now", right_div);
      this.temperature_now_minus = create_element("div", "temperature_now_minus", temperature_now);
      this.temperature_now_minus.textContent = "-";
      this.temperature_now_number = create_element("div", "temperature_now_number", temperature_now);
      this.temperature_now_number.textContent = "0°";
      city_and_date = create_element("div", "city_and_date", right_div);
      this.city = create_element("div", "city", city_and_date);
      this.city_now = create_element("div", "city_now", this.city);
      this.city_now.textContent = _("choose city");
      this.more_city_img = create_img("more_city_img", this.img_url_first + "ar.png", this.city);
      this.date = create_element("div", "date", city_and_date);
      this.date.textContent = _("loading.............");
      this.refresh = create_img("refresh", this.img_url_first + "refresh.png", this.element);
      return this.refresh.addEventListener("click", function() {
        _this.refresh.style.backgroundColor = "gray";
        if (localStorage.getItem("cityid_storage") !== null) {
          return _this.weathergui_update(localStorage.getItem("cityid_storage"));
        }
      }, this.element.addEventListener("dragstart", function() {
        var bottom_distance;

        clearTimeout(_this.display_city_menu_id);
        _this.rightclick.style.display = "none";
        _this.more_city_menu.style.display = "none";
        _this.more_weather_menu.style.display = "none";
        bottom_distance = window.screen.availHeight - _this.element.getBoundingClientRect().bottom;
        if (bottom_distance < 330) {
          _this.rightclick.style.top = -160;
          _this.more_city_menu.style.top = -252;
          return _this.more_weather_menu.style.top = -213;
        } else {
          _this.rightclick.style.top = 70;
          _this.more_city_menu.style.top = 70;
          return _this.more_weather_menu.style.top = 70;
        }
      }));
    };

    Weather.prototype.more_weather_build = function() {
      var img_more_url_init, img_now_url_init, week_init,
        _this = this;

      week_init = _("Sun");
      img_now_url_init = this.img_url_first + "48/T" + "0\u6674" + ".png";
      img_more_url_init = this.img_url_first + "24/T" + "0\u6674" + ".png";
      this.more_weather_menu = create_element("div", "more_weather_menu", this.element);
      this.more_weather_menu.style.display = "none";
      this.first_day_weather_data = create_element("div", "first_day_weather_data", this.more_weather_menu);
      this.week1 = create_element("a", "week1", this.first_day_weather_data);
      this.week1.textContent = week_init;
      this.pic1 = create_img("pic1", img_more_url_init, this.first_day_weather_data);
      this.temperature1 = create_element("a", "temperature1", this.first_day_weather_data);
      this.temperature1.textContent = "22℃~10℃";
      this.second_day_weather_data = create_element("div", "second_day_weather_data", this.more_weather_menu);
      this.week2 = create_element("a", "week2", this.second_day_weather_data);
      this.week2.textContent = week_init;
      this.pic2 = create_img("pic2", img_more_url_init, this.second_day_weather_data);
      this.temperature2 = create_element("a", "temperature2", this.second_day_weather_data);
      this.temperature2.textContent = "22℃~10℃";
      this.third_day_weather_data = create_element("div", "third_day_weather_data", this.more_weather_menu);
      this.week3 = create_element("a", "week3", this.third_day_weather_data);
      this.week3.textContent = week_init;
      this.pic3 = create_img("pic3", img_more_url_init, this.third_day_weather_data);
      this.temperature3 = create_element("a", "temperature3", this.third_day_weather_data);
      this.temperature3.textContent = "22℃~10℃";
      this.fourth_day_weather_data = create_element("div", "fourth_day_weather_data", this.more_weather_menu);
      this.week4 = create_element("a", "week4", this.fourth_day_weather_data);
      this.week4.textContent = week_init;
      this.pic4 = create_img("pic4", img_more_url_init, this.fourth_day_weather_data);
      this.temperature4 = create_element("a", "temperature4", this.fourth_day_weather_data);
      this.temperature4.textContent = "22℃~10℃";
      this.fifth_day_weather_data = create_element("div", "fifth_day_weather_data", this.more_weather_menu);
      this.week5 = create_element("a", "week5", this.fifth_day_weather_data);
      this.week5.textContent = week_init;
      this.pic5 = create_img("pic5", img_more_url_init, this.fifth_day_weather_data);
      this.temperature5 = create_element("a", "temperature5", this.fifth_day_weather_data);
      this.temperature5.textContent = "22℃~10℃";
      this.sixth_day_weather_data = create_element("div", "sixth_day_weather_data", this.more_weather_menu);
      this.week6 = create_element("a", "week6", this.sixth_day_weather_data);
      this.week6.textContent = week_init;
      this.pic6 = create_img("pic6", img_more_url_init, this.sixth_day_weather_data);
      this.temperature6 = create_element("a", "temperature6", this.sixth_day_weather_data);
      this.temperature6.textContent = "22℃~10℃";
      return this.date.addEventListener("click", function() {
        var bottom_distance;

        clearTimeout(_this.display_city_menu_id);
        if (_this.more_weather_menu.style.display === "none") {
          bottom_distance = window.screen.availHeight - _this.element.getBoundingClientRect().bottom;
          if (bottom_distance < 200) {
            _this.more_weather_menu.style.top = -213;
          } else {
            _this.more_weather_menu.style.top = 70;
          }
          _this.more_weather_menu.style.display = "block";
          _this.more_city_menu.style.display = "none";
          return _this.more_weather_menu.style.zIndex = "65535";
        } else {
          _this.more_weather_menu.style.display = "none";
          _this.more_city_menu.style.display = "none";
          return _this.more_weather_menu.style.zIndex = "0";
        }
      });
    };

    Weather.prototype.more_city_build = function() {
      var _this = this;

      this.str_provinit = _("--province--");
      this.str_cityinit = _("--city--");
      this.str_distinit = _("--county--");
      this.more_city_menu = create_element("div", "more_city_menu", this.element);
      this.more_city_menu.style.display = "none";
      this.chooseprov = create_element("select", "chooseprov", this.more_city_menu);
      this.choosecity = create_element("select", "choosecity", this.more_city_menu);
      this.choosedist = create_element("select", "choosedist", this.more_city_menu);
      this.city.addEventListener("click", function() {
        var bottom_distance, cityinit, distinit, i, length, provinit;

        if (_this.more_city_menu.style.display === "none") {
          bottom_distance = window.screen.availHeight - _this.element.getBoundingClientRect().bottom;
          if (bottom_distance < 200) {
            _this.more_city_menu.style.top = -252;
          } else {
            _this.more_city_menu.style.top = 70;
          }
          _this.more_city_menu.style.display = "block";
          _this.more_weather_menu.style.display = "none";
          _this.more_city_menu.style.zIndex = "65535";
          _this.display_city_menu_id = setTimeout(function() {
            return _this.more_city_menu.style.display = "none";
          }, 4000);
        } else {
          _this.more_city_menu.style.display = "none";
          _this.more_weather_menu.style.display = "none";
          _this.more_city_menu.style.zIndex = "0";
          clearTimeout(_this.display_city_menu_id);
        }
        _this.chooseprov.options.length = 0;
        provinit = create_element("option", "provinit", _this.chooseprov);
        provinit.innerText = _this.str_provinit;
        provinit.selected = "true";
        i = 0;
        while (i < cities.length) {
          _this.chooseprov.options.add(new Option(cities[i].name, cities[i++].id));
        }
        length = _this.chooseprov.options.length;
        _this.chooseprov.size = (length < 13 ? length : 13);
        _this.choosecity.size = 1;
        _this.choosecity.options.length = 0;
        cityinit = create_element("option", "cityinit", _this.choosecity);
        cityinit.innerText = _this.str_cityinit;
        cityinit.selected = "true";
        _this.choosedist.size = 1;
        _this.choosedist.options.length = 0;
        distinit = create_element("option", "distinit", _this.choosedist);
        distinit.innerText = _this.str_distinit;
        return distinit.selected = "true";
      });
      this.more_city_menu.addEventListener("click", function() {
        return clearTimeout(_this.display_city_menu_id);
      });
      return this.chooseprov.addEventListener("change", function() {
        var data, provIndex, provvalue;

        provIndex = _this.chooseprov.selectedIndex;
        if (provIndex === -1) {
          return _this.chooseprov.options.remove(provIndex);
        } else {
          provvalue = _this.chooseprov.options[provIndex].value;
          if (provvalue !== _this.str_provinit) {
            return data = _this.read_data_from_json(provvalue);
          }
        }
      });
    };

    Weather.prototype.rightclick_build = function() {
      var about, feedback, refresh_context, share, weather_close,
        _this = this;

      this.rightclick = create_element("div", "rightclick", this.element);
      this.rightclick.style.display = "none";
      weather_close = create_element("div", "weather_close", this.rightclick);
      refresh_context = create_element("div", "refresh_context", this.rightclick);
      share = create_element("div", "share", this.rightclick);
      feedback = create_element("div", "feedback", this.rightclick);
      about = create_element("div", "about", this.rightclick);
      weather_close.innerText = _("close");
      refresh_context.innerText = _("refresh");
      share.innerText = _("share");
      feedback.innerText = _("feedback");
      about.innerText = _("about");
      this.element.addEventListener("contextmenu", function(evt) {
        var bottom_distance;

        clearTimeout(_this.display_city_menu_id);
        _this.more_weather_menu.style.display = "none";
        _this.more_city_menu.style.display = "none";
        if (_this.rightclick.style.display === "none") {
          bottom_distance = window.screen.availHeight - _this.element.getBoundingClientRect().bottom;
          if (bottom_distance < 200) {
            _this.rightclick.style.top = -160;
          } else {
            _this.rightclick.style.top = 70;
          }
          _this.rightclick.style.display = "block";
          return _this.rightclick.style.zIndex = "65535";
        } else {
          return _this.rightclick.style.display = "none";
        }
      });
      this.element.addEventListener("click", function() {
        if (_this.rightclick.style.display === "block") {
          _this.rightclick.style.display = "none";
          return _this.rightclick.style.zIndex = "0";
        }
      });
      weather_close.addEventListener("click", function() {
        var msg_close;

        _this.element.style.display = "none";
        msg_close = create_element("POST", "msg_close", weather_close);
        return msg_close.innerText = "close";
      });
      refresh_context.addEventListener("click", function() {
        _this.refresh.style.backgroundColor = "gray";
        if (localStorage.getItem("cityid_storage") !== null) {
          return _this.weathergui_update(localStorage.getItem("cityid_storage"));
        }
      });
      share.addEventListener("click", function() {
        return alert(_("Please wait ......"));
      });
      feedback.addEventListener("click", function() {
        var feedbackmsg;

        feedbackmsg = prompt(_("Thanks for your feedback～～"), "");
        if (feedbackmsg !== null && feedbackmsg !== "") {
          return echo("feedbackmsg:" + feedbackmsg);
        }
      });
      return about.addEventListener("click", function() {
        var str_about_msg;

        str_about_msg = _("deepin weather widget 1.0.0") + "\n" + "Copyright (c) 2011 ~ 2012 Deepin, Inc." + "\n" + "www.linuxdeepin.com";
        return alert(str_about_msg);
      });
    };

    Weather.prototype.weathergui_init = function() {
      var cityid, loader;

      loader = new Loader;
      loader.addcss('desktop_plugin/weather/weather.css').load();
      this.weather_style_build();
      this.more_weather_build();
      this.more_city_build();
      this.rightclick_build();
      cityid = localStorage.getItem("cityid_storage");
      if (cityid === null) {
        return this.get_client_cityid(ip_url1());
      } else {
        return this.weathergui_update(cityid);
      }
    };

    Weather.prototype.ajax = function(url, method, callback, asyn) {
      var xhr,
        _this = this;

      if (asyn == null) {
        asyn = true;
      }
      xhr = new XMLHttpRequest();
      xhr.open(method, url, asyn);
      xhr.send(null);
      return xhr.onreadystatechange = function() {
        if (xhr.readyState === 4 && xhr.status === 200) {
          return typeof callback === "function" ? callback(xhr) : void 0;
        } else if (xhr.status !== 200) {
          return echo("XMLHttpRequest can't receive data.");
        }
      };
    };

    Weather.prototype.read_data_from_json = function(id) {
      var url, xhr,
        _this = this;

      xhr = new XMLHttpRequest();
      url = "desktop_plugin/weather/city/" + id + ".json";
      xhr.open("GET", url, true);
      xhr.send(null);
      return xhr.onreadystatechange = function() {
        var data;

        if (xhr.readyState === 4) {
          data = JSON.parse(xhr.responseText);
          return _this.cityadd(data[id].data);
        }
      };
    };

    Weather.prototype.cityadd = function(data) {
      var i, length,
        _this = this;

      this.choosecity.options.length = 1;
      for (i in data) {
        this.choosecity.options.add(new Option(data[i].name, i));
      }
      length = this.choosecity.options.length;
      this.choosecity.size = (length < 13 ? length : 13);
      return this.choosecity.onchange = function() {
        var cityIndex, cityvalue;

        cityIndex = _this.choosecity.selectedIndex;
        if (cityIndex === -1) {
          return _this.choosecity.options.remove(cityIndex);
        } else {
          cityvalue = _this.choosecity.options[cityIndex].value;
          if (cityvalue !== _this.str_cityinit) {
            return _this.distadd(data[cityvalue].data);
          }
        }
      };
    };

    Weather.prototype.distadd = function(data) {
      var i, length,
        _this = this;

      this.choosedist.options.length = 1;
      for (i in data) {
        this.choosedist.options.add(new Option(data[i].name, i));
      }
      length = this.choosedist.options.length;
      this.choosedist.size = (length < 13 ? length : 13);
      return this.choosedist.onchange = function() {
        var cityid_choose, distIndex, distvalue;

        clearInterval(_this.auto_update_cityid_choose);
        _this.more_city_menu.style.display = "none";
        distIndex = _this.choosedist.selectedIndex;
        if (distIndex === -1) {
          return _this.choosedist.options.remove(distIndex);
        } else {
          distvalue = _this.choosedist.options[distIndex].value;
          if (distvalue !== _this.str_distinit) {
            cityid_choose = data[distvalue].data;
            localStorage.setItem("cityid_choose_storage", cityid_choose);
            cityid_choose = localStorage.getItem("cityid_choose_storage");
            if (cityid_choose !== null) {
              return _this.auto_update_cityid_choose = setInterval(_this.weathergui_update(cityid_choose), 600000);
            }
          }
        }
      };
    };

    Weather.prototype.get_client_cityid = function(ip_url1) {
      var _this = this;

      return this.ajax(ip_url1, "GET", function(xhr) {
        var ip, str;

        str = xhr.responseText;
        if (str[0] === '1') {
          ip = str.slice(2, 12);
          echo("ip start :" + ip);
          return _this.ajax(ip_url2(ip), "GET", function(xhr) {
            var ci, cityid_client, client_ip_city, provin, remote_ip_info;

            client_ip_city = xhr.responseText;
            remote_ip_info = JSON.parse(client_ip_city.slice(21, client_ip_city.length));
            if (remote_ip_info.ret === 1) {
              echo("remote_ip_info.province:" + remote_ip_info.province);
              echo("remote_ip_info.city:" + remote_ip_info.city);
              for (provin in allname.data) {
                if (allname.data[provin].prov === remote_ip_info.province) {
                  for (ci in allname.data[provin].city) {
                    if (allname.data[provin].city[ci].cityname === remote_ip_info.city) {
                      cityid_client = allname.data[provin].city[ci].code;
                      echo("cityid_client:" + cityid_client);
                      localStorage.setItem("cityid_client_storage", cityid_client);
                      cityid_client = localStorage.getItem("cityid_client_storage");
                      if (cityid_client !== null) {
                        _this.weathergui_update(cityid_client);
                      }
                      return cityid_client;
                    }
                  }
                }
              }
            } else {
              return echo("sina iplookup can't find the matched location json by ip");
            }
          });
        } else {
          return echo("sina iplookup can't get the client ip");
        }
      });
    };

    Weather.prototype.weathergui_update = function(id) {
      var cityid,
        _this = this;

      localStorage.setItem("cityid_storage", id);
      cityid = localStorage.getItem("cityid_storage");
      this.ajax(now_weather_url(cityid), "GET", function(xhr) {
        var temp_now, weather_data_now;

        localStorage.setItem("weather_data_now_storage", xhr.responseText);
        weather_data_now = JSON.parse(localStorage.getItem("weather_data_now_storage"));
        temp_now = weather_data_now.weatherinfo.temp;
        _this.time_update = weather_data_now.weatherinfo.time;
        _this.city_now.textContent = weather_data_now.weatherinfo.city;
        if (temp_now === "\u6682\u65e0\u5b9e\u51b5") {
          return _this.temperature_now_number.textContent = _("NO");
        } else {
          if (temp_now < -10) {
            _this.temperature_now_minus.style.opacity = 0.8;
            return _this.temperature_now_number.textContent = -temp_now + "°";
          } else {
            _this.temperature_now_minus.style.opacity = 0;
            return _this.temperature_now_number.textContent = temp_now + "°";
          }
        }
      });
      return this.ajax(more_weather_url(cityid), "GET", function(xhr) {
        var i_week, str_data, weather_data, week_n, week_name, week_show;

        localStorage.setItem("weather_data_storage", xhr.responseText);
        weather_data = JSON.parse(localStorage.getItem("weather_data_storage"));
        _this.weather_data = weather_data;
        i_week = 0;
        week_name = ["\u661f\u671f\u65e5", "\u661f\u671f\u4e00", "\u661f\u671f\u4e8c", "\u661f\u671f\u4e09", "\u661f\u671f\u56db", "\u661f\u671f\u4e94", "\u661f\u671f\u516d"];
        week_show = [_("Sun"), _("Mon"), _("Tue"), _("Wed"), _("Thu"), _("Fri"), _("Sat")];
        while (i_week < week_name.length) {
          if (weather_data.weatherinfo.week === week_name[i_week]) {
            break;
          }
          i_week++;
        }
        week_n = i_week;
        str_data = weather_data.weatherinfo.date_y;
        _this.date.textContent = str_data.substring(0, str_data.indexOf("\u5e74")) + "." + str_data.substring(str_data.indexOf("\u5e74") + 1, str_data.indexOf("\u6708")) + "." + str_data.substring(str_data.indexOf("\u6708") + 1, str_data.indexOf("\u65e5")) + week_show[week_n % 7];
        _this.weather_now_pic.src = _this.img_url_first + "48/T" + weather_data.weatherinfo.img_single + weather_data.weatherinfo.img_title_single + ".png";
        _this.week1.textContent = week_show[week_n % 7];
        _this.pic1.src = _this.weather_more_pic_src(1);
        _this.temperature1.textContent = weather_data.weatherinfo.temp1;
        _this.week2.textContent = week_show[(week_n + 1) % 7];
        _this.pic2.src = _this.weather_more_pic_src(2);
        _this.temperature2.textContent = weather_data.weatherinfo.temp2;
        _this.week3.textContent = week_show[(week_n + 2) % 7];
        _this.pic3.src = _this.weather_more_pic_src(3);
        _this.temperature3.textContent = weather_data.weatherinfo.temp3;
        _this.week4.textContent = week_show[(week_n + 3) % 7];
        _this.pic4.src = _this.weather_more_pic_src(4);
        _this.temperature4.textContent = weather_data.weatherinfo.temp4;
        _this.week5.textContent = week_show[(week_n + 4) % 7];
        _this.pic5.src = _this.weather_more_pic_src(5);
        _this.temperature5.textContent = weather_data.weatherinfo.temp5;
        _this.week6.textContent = week_show[(week_n + 5) % 7];
        _this.pic6.src = _this.weather_more_pic_src(6);
        _this.temperature6.textContent = weather_data.weatherinfo.temp6;
        return _this.refresh.style.backgroundColor = null;
      });
    };

    Weather.prototype.weather_more_pic_src = function(i) {
      var hours_now, img_behind, img_front, src, time, weather_data;

      i = i * 2 - 1;
      weather_data = this.weather_data;
      src = null;
      time = new Date();
      hours_now = time.getHours();
      img_front = [weather_data.weatherinfo.img_single, weather_data.weatherinfo.img1, weather_data.weatherinfo.img2, weather_data.weatherinfo.img3, weather_data.weatherinfo.img4, weather_data.weatherinfo.img5, weather_data.weatherinfo.img6, weather_data.weatherinfo.img7, weather_data.weatherinfo.img8, weather_data.weatherinfo.img9, weather_data.weatherinfo.img10, weather_data.weatherinfo.img11, weather_data.weatherinfo.img12];
      img_behind = [weather_data.weatherinfo.img_title_single, weather_data.weatherinfo.img_title1, weather_data.weatherinfo.img_title2, weather_data.weatherinfo.img_title3, weather_data.weatherinfo.img_title4, weather_data.weatherinfo.img_title5, weather_data.weatherinfo.img_title6, weather_data.weatherinfo.img_title7, weather_data.weatherinfo.img_title8, weather_data.weatherinfo.img_title9, weather_data.weatherinfo.img_title10, weather_data.weatherinfo.img_title11, weather_data.weatherinfo.img_title12];
      if (img_front[i + 1] === "99") {
        img_front[i + 1] = img_front[i];
      }
      if (hours_now < 12) {
        src = this.img_url_first + "24/T" + img_front[i] + img_behind[i] + ".png";
      } else {
        src = this.img_url_first + "24/T" + img_front[i + 1] + img_behind[i + 1] + ".png";
      }
      return src;
    };

    return Weather;

  })();

  window.desktop_plugin = [];

  plugins = window.desktop_plugin;

  weather = new Weather;

  plugins.push(weather);

}).call(this);
