# com_dir = ../../../common/js
com_dir = /usr/share/dde/resources/common/js

all: ${com_dir}/utils.coffee ${com_dir}/module.coffee ${com_dir}/widget.coffee  ${com_dir}/animation.coffee clock.coffee
	coffee -cj clock.js $^
