com_dir = ../../common/js
com_coffee = ${com_dir}/utils.coffee ${com_dir}/animation.coffee ${com_dir}/module.coffee ${com_dir}/widget.coffee ${com_dir}/selector.coffee ${com_dir}/plugin.coffee
all: ${com_coffee} common.coffee grid.coffee signals.coffee desktop_item.coffee dispatch.coffee  main.coffee plugin.coffee
	coffee -cj desktop.js $^
