NODE_PATH?=../../../node_modules
coffee?=${NODE_PATH}/coffee-script/bin/coffee
com_dir=../../common/js
com_coffee = ${com_dir}/strict_mode.coffee\
	     ${com_dir}/config.coffee \
	     ${com_dir}/utils.coffee \
	     ${com_dir}/animation.coffee \
	     ${com_dir}/module.coffee \
	     ${com_dir}/widget.coffee \
	     ${com_dir}/selector.coffee \

# optional coffee script
# ${com_dir}/uninstaller.coffee
# ${com_dir}/accounts.coffee
# ${com_dir}/audioplay.coffee
# ${com_dir}/plugin.coffee
# ${com_dir}/power.coffee
# ${com_dir}/uninstaller.coffee
