
NODE_PATH?=../../../node_modules
coffee?=${NODE_PATH}/coffee-script/bin/coffee
com_dir=../../common/js
com_coffee = ${com_dir}/config.coffee \
	     ${com_dir}/utils.coffee \
	     ${com_dir}/animation.coffee \
	     ${com_dir}/module.coffee \
	     ${com_dir}/widget.coffee \
	     ${com_dir}/selector.coffee \
	     ${com_dir}/tooltip.coffee \
	     ${com_dir}/menu.coffee \
	     ${com_dir}/uninstaller.coffee
