#!/usr/bin/python

import glob
import os
import re

except_dirs = ["dbus_test", "memory_test", "dominant_color"]
app = "dde-workspace"


def get_files():
    coffee_files = []
    c_files = []

    for d in os.listdir("../resources"):
        if  d == "common" or d in except_dirs:
            continue

        coffee_dir = "../resources/%s/js/" % d
        for dirpath, dirnames, filenames in os.walk(coffee_dir):
            for filename in filenames:
                if filename.endswith(".coffee"):
                    coffee_files.append(os.path.join(dirpath, filename))

    #TODO:Here add your app coffee files in special dir
    coffee_files.append("../resources/common/js/uninstaller.coffee")

    for d in os.listdir("../app"):
        if d not in except_dirs:
            c_files += glob.glob("../app/%s/*.c" % d);
            c_files += glob.glob("../app/%s/*.h" % d);

    #TODO:Here add your app c files in special dir
    for lib in [
            "../lib/dentry/*.c",
            "../lib/dentry/*.h",
            "../lib/category.c",
            ]:
        c_files.extend(glob.glob(lib))

    c_files.sort()
    coffee_files.sort()
    return coffee_files, c_files

def scan_pot(coffee_files, c_files):
    os.system("rm %s.pot" % app)
    os.system("touch %s.pot" % app)

    cmd= "xgettext --from-code=utf-8 -L python -j -o %s.pot " % app + " ".join(coffee_files)
    os.system(cmd)

    cmd = "xgettext --from-code=utf-8 -k_ -j -o %s.pot " % app + " ".join(c_files)
    os.system(cmd)

if __name__ == '__main__':
    scan_pot(*get_files())
