#!/usr/bin/python2

base_dir = "../resources/"
scan_dir = ["greeter/js/*.coffee", "desktop/js/*.coffee", "dock/js/*.coffee", "launcher/js/*.coffee"]

other_files = ["../app/desktop/desktop.c"]

import glob
import os

files = []
for i in scan_dir:
    tmp = glob.glob(base_dir + i)
    files = files + tmp




cmd= "xgettext -L python -j -o zh_CN.po " + " ".join(files)
os.system(cmd)

cmd = "xgettext -k_ -j -o zh_CN.po " + " ".join(other_files)
os.system(cmd)
