MAX_SCALE = 1
ITEM_HEIGHT = 60.0
ITEM_WIDTH = 68.0

ICON_WIDTH = 48.0
ICON_HEIGHT = 48.0
ICON_BORDER = 2.0

DOCK_HEIGHT = 30.0

BOARD_IMG_PATH = "img/board.png"

BOARD_IMG_MARGIN_BOTTOM = 6.0

INDICATER_WIDTH = 66.0
INDICATER_HEIGHT = 52.0

THREE_MARGIN_STEP = 3.0
TWO_MARGIN_STEP = 2.0


PREVIEW_BORDER_LENGTH = 5.0
PREVIEW_CANVAS_WIDTH = 190.0
PREVIEW_CANVAS_HEIGHT = 110.0
PREVIEW_WINDOW_WIDTH = 230.0
PREVIEW_WINDOW_HEIGHT = 160.0

#below should not modify
INDICATER_IMG_MARGIN_LEFT = "#{(ITEM_WIDTH - INDICATER_WIDTH) / ITEM_WIDTH *100}%"
BOARD_IMG_MARGIN_LEFT = "#{((ITEM_WIDTH - ICON_WIDTH) / 2) / ITEM_WIDTH  * 100}%"
BOARD_IMG_MARGIN_LEFT_TWO_RIGHT = "#{((ITEM_WIDTH - ICON_WIDTH) / 2 + TWO_MARGIN_STEP) / ITEM_WIDTH  * 100}%"
BOARD_IMG_MARGIN_LEFT_TWO_LEFT = "#{((ITEM_WIDTH - ICON_WIDTH) / 2 - TWO_MARGIN_STEP) / ITEM_WIDTH  * 100}%"

BOARD_IMG_MARGIN_LEFT_THREE_RIGHT = "#{((ITEM_WIDTH - ICON_WIDTH) / 2 + THREE_MARGIN_STEP) / ITEM_WIDTH  * 100}%"
BOARD_IMG_MARGIN_LEFT_THREE_LEFT = "#{((ITEM_WIDTH - ICON_WIDTH) / 2 - THREE_MARGIN_STEP) / ITEM_WIDTH  * 100}%"

IN_INIT = true

try
    NOT_FOUND_ICON = DCore.get_theme_icon("invalid-dock_app", 48)
catch e
    NOT_FOUND_ICON = "img/not_found.png"

ICON_SCALE = MAX_SCALE  #this will be modify on runtime
