BOARD_HEIGHT = 60.0
BOARD_WIDTH = 68.0
BOARD_IMG_WIDTH = 48.0
BOARD_IMG_HEIGHT = 48.0
BOARD_IMG_MARGIN_ONE_SPACE = 3.0
APP_IMG_WIDTH = 36.0
APP_IMG_HEIGHT = 36.0

BOARD_MARGIN_BOTTOM = 6.0


DOCK_HEIGHT = 30.0


BOARD_IMG_PATH = "img/board.png"
_left_space = (BOARD_WIDTH - BOARD_IMG_WIDTH)/2.0
APP_IMG_LEFT = "#{(BOARD_WIDTH - APP_IMG_WIDTH) * 0.5 / BOARD_WIDTH * 100.0}%"
BOARD_IMG1_LEFT = "#{(BOARD_WIDTH - BOARD_IMG_WIDTH) * 0.5 / BOARD_WIDTH * 100.0}%"
BOARD_IMG2_LEFT = "#{(_left_space + BOARD_IMG_MARGIN_ONE_SPACE) / BOARD_WIDTH * 100.0}%"
BOARD_IMG3_LEFT = "#{(_left_space + BOARD_IMG_MARGIN_ONE_SPACE + BOARD_IMG_MARGIN_ONE_SPACE )/ BOARD_WIDTH * 100.0}%"

