// Generated by CoffeeScript 1.3.3
var DesktopEntry, Folder, IconGroup, Item,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Item = (function(_super) {

  __extends(Item, _super);

  Item.included(Recordable, ["id", "x", "y"]);

  function Item(name, icon, exec) {
    this.name = name;
    this.icon = icon;
    this.exec = exec;
    this.id = DCore.gen_id(this.name + this.icon + this.exec);
    this.itemTemp = "icontemp";
    this.itemContainer = "itemContainer";
    this.load();
  }

  Item.prototype.render = function() {
    var _this = this;
    $("#" + this.itemContainer).append($("#" + this.itemTemp).render({
      "class": "item",
      "id": this.id,
      "name": this.name,
      "icon": this.icon,
      "exec": this.exec
    }));
    return this._$().draggable({
      stop: function(event, ui) {
        return _this.save();
      }
    }).dblclick(function() {
      return DCore.run_command($(this)[0].getAttribute('exec'));
    });
  };

  return Item;

})(Widget);

DesktopEntry = (function(_super) {

  __extends(DesktopEntry, _super);

  function DesktopEntry() {
    return DesktopEntry.__super__.constructor.apply(this, arguments);
  }

  return DesktopEntry;

})(Item);

Folder = (function(_super) {

  __extends(Folder, _super);

  function Folder() {
    return Folder.__super__.constructor.apply(this, arguments);
  }

  return Folder;

})(Item);

IconGroup = (function(_super) {

  __extends(IconGroup, _super);

  function IconGroup() {
    return IconGroup.__super__.constructor.apply(this, arguments);
  }

  return IconGroup;

})(Item);
