/**
 * Copyright (c) 2011 ~ 2013 Deepin, Inc.
 *               2013 ~ 2013 Liqiang Lee
 *
 * Author:      Liqiang Lee <liliqiang@linuxdeepin.com>
 * Maintainer:  Liqiang Lee <liliqiang@linuxdeepin.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 **/

#include "x_category.h"

#define NETWORK_ID 0
#define MULTIMEDIA_ID 1
#define GAMES_ID 2
#define GRAPHICS_ID 3
#define PRODUCTIVITY_ID 4
#define INDUSTRY_ID 5
#define EDUCATION_ID 6
#define DEVELOPMENT_ID 7
#define SYSTEM_ID 8
#define UTILITIES_ID 9

XCategory x_category_name_index_map[X_CATEGORY_NUM] = {
    {"internet", NETWORK_ID},
    {"webbrowser", NETWORK_ID},
    {"email", NETWORK_ID},
    {"contactmanagement", NETWORK_ID},
    {"filetransfer", NETWORK_ID},
    {"p2p", NETWORK_ID},
    {"instantmessaging", NETWORK_ID},
    {"chat", NETWORK_ID},
    {"videoconference", NETWORK_ID},
    {"ircclient", NETWORK_ID},
    {"news", NETWORK_ID},
    {"remoteaccess", NETWORK_ID},
    {"multimedia", MULTIMEDIA_ID},
    {"tv", MULTIMEDIA_ID},
    {"audio", MULTIMEDIA_ID},
    {"video", MULTIMEDIA_ID},
    {"audiovideo", MULTIMEDIA_ID},
    {"x-jack", MULTIMEDIA_ID},
    {"x-alsa", MULTIMEDIA_ID},
    {"x-multitrack", MULTIMEDIA_ID},
    {"x-sound", MULTIMEDIA_ID},
    {"audiovideoediting", MULTIMEDIA_ID},
    {"cd", MULTIMEDIA_ID},
    {"discburning", MULTIMEDIA_ID},
    {"midi", MULTIMEDIA_ID},
    {"x-midi", MULTIMEDIA_ID},
    {"mixer", MULTIMEDIA_ID},
    {"player", MULTIMEDIA_ID},
    {"music", MULTIMEDIA_ID},
    {"recorder", MULTIMEDIA_ID},
    {"sequencer", MULTIMEDIA_ID},
    {"x-sequencers", MULTIMEDIA_ID},
    {"x-suse-sequencer", MULTIMEDIA_ID},
    {"tuner", MULTIMEDIA_ID},
    {"game", GAMES_ID},
    {"amusement", GAMES_ID},
    {"actiongame", GAMES_ID},
    {"adventuregame", GAMES_ID},
    {"arcadegame", GAMES_ID},
    {"boardgame", GAMES_ID},
    {"cardgame", GAMES_ID},
    {"emulator", GAMES_ID},
    {"x-debian-applications-emulators", GAMES_ID},
    {"simulation", GAMES_ID},
    {"kidsgame", GAMES_ID},
    {"logicgame", GAMES_ID},
    {"puzzlegame", GAMES_ID},
    {"blocksgame", GAMES_ID},
    {"x-suse-core-game", GAMES_ID},
    {"roleplaying", GAMES_ID},
    {"sportsgame", GAMES_ID},
    {"strategygame", GAMES_ID},
    {"graphics", GRAPHICS_ID},
    {"2dgraphics", GRAPHICS_ID},
    {"3dgraphics", GRAPHICS_ID},
    {"imageprocessing", GRAPHICS_ID},
    {"ocr", GRAPHICS_ID},
    {"photography", GRAPHICS_ID},
    {"rastergraphics", GRAPHICS_ID},
    {"vectorgraphics", GRAPHICS_ID},
    {"x-geeqie", GRAPHICS_ID},
    {"viewer", GRAPHICS_ID},
    {"spreadsheet", PRODUCTIVITY_ID},
    {"office", PRODUCTIVITY_ID},
    {"x-suse-core-office", PRODUCTIVITY_ID},
    {"x-mandrivalinux-office-other", PRODUCTIVITY_ID},
    {"x-turbolinux-office", PRODUCTIVITY_ID},
    {"wordprocessor", PRODUCTIVITY_ID},
    {"projectmanagement", PRODUCTIVITY_ID},
    {"chart", PRODUCTIVITY_ID},
    {"numericalanalysis", PRODUCTIVITY_ID},
    {"presentation", PRODUCTIVITY_ID},
    {"scanning", PRODUCTIVITY_ID},
    {"printing", PRODUCTIVITY_ID},
    {"engineering", INDUSTRY_ID},
    {"telephonytools", INDUSTRY_ID},
    {"telephony", INDUSTRY_ID},
    {"technical", INDUSTRY_ID},
    {"finance", INDUSTRY_ID},
    {"hamradio", INDUSTRY_ID},
    {"medicalsoftware", INDUSTRY_ID},
    {"x-mandriva-office-publishing", INDUSTRY_ID},
    {"publishing", INDUSTRY_ID},
    {"x-kde-edu-misc", EDUCATION_ID},
    {"education", EDUCATION_ID},
    {"art", EDUCATION_ID},
    {"literature", EDUCATION_ID},
    {"translation", EDUCATION_ID},
    {"dictionary", EDUCATION_ID},
    {"x-religion", EDUCATION_ID},
    {"x-bible", EDUCATION_ID},
    {"x-islamic-software", EDUCATION_ID},
    {"x-quran", EDUCATION_ID},
    {"artificialintelligence", EDUCATION_ID},
    {"electricity", EDUCATION_ID},
    {"robotics", EDUCATION_ID},
    {"geography", EDUCATION_ID},
    {"computerscience", EDUCATION_ID},
    {"math", EDUCATION_ID},
    {"biology", EDUCATION_ID},
    {"geoscience", EDUCATION_ID},
    {"physics", EDUCATION_ID},
    {"meteorology", EDUCATION_ID},
    {"chemistry", EDUCATION_ID},
    {"electronics", EDUCATION_ID},
    {"geology", EDUCATION_ID},
    {"astronomy", EDUCATION_ID},
    {"science", EDUCATION_ID},
    {"development", DEVELOPMENT_ID},
    {"debugger", DEVELOPMENT_ID},
    {"ide", DEVELOPMENT_ID},
    {"building", DEVELOPMENT_ID},
    {"guidesigner", DEVELOPMENT_ID},
    {"webdevelopment", DEVELOPMENT_ID},
    {"revisioncontrol", DEVELOPMENT_ID},
    {"system", SYSTEM_ID},
    {"trayicon", SYSTEM_ID},
    {"x-lxde-settings", SYSTEM_ID},
    {"x-xfce-toplevel", SYSTEM_ID},
    {"x-xfcesettingsdialog", SYSTEM_ID},
    {"x-xfce", SYSTEM_ID},
    {"x-kde-utilities-pim", SYSTEM_ID},
    {"x-kde-internet", SYSTEM_ID},
    {"x-kde-more", SYSTEM_ID},
    {"x-kde-utilities-peripherals", SYSTEM_ID},
    {"kde", SYSTEM_ID},
    {"x-kde-utilities-file", SYSTEM_ID},
    {"x-kde-utilities-desktop", SYSTEM_ID},
    {"x-gnome-networksettings", SYSTEM_ID},
    {"gnome", SYSTEM_ID},
    {"x-gnome-settings-panel", SYSTEM_ID},
    {"x-gnome-personalsettings", SYSTEM_ID},
    {"x-gnome-systemsettings", SYSTEM_ID},
    {"desktoputility", SYSTEM_ID},
    {"x-misc", SYSTEM_ID},
    {"x-suse-core", SYSTEM_ID},
    {"x-red-hat-base-only", SYSTEM_ID},
    {"x-novell-main", SYSTEM_ID},
    {"x-red-hat-extra", SYSTEM_ID},
    {"x-suse-yast", SYSTEM_ID},
    {"x-sun-supported", SYSTEM_ID},
    {"x-suse-yast-high_availability", SYSTEM_ID},
    {"x-suse-controlcenter-lookandfeel", SYSTEM_ID},
    {"x-suse-controlcenter-system", SYSTEM_ID},
    {"x-red-hat-serverconfig", SYSTEM_ID},
    {"x-mandrivalinux-system-archiving-backup", SYSTEM_ID},
    {"x-suse-backup", SYSTEM_ID},
    {"x-red-hat-base", SYSTEM_ID},
    {"panel", SYSTEM_ID},
    {"x-gnustep", SYSTEM_ID},
    {"x-bluetooth", SYSTEM_ID},
    {"x-ximian-main", SYSTEM_ID},
    {"x-synthesis", SYSTEM_ID},
    {"x-digital_processing", SYSTEM_ID},
    {"desktopsettings", SYSTEM_ID},
    {"monitor", SYSTEM_ID},
    {"dialup", SYSTEM_ID},
    {"x-mandrivalinux-internet-other", SYSTEM_ID},
    {"packagemanager", SYSTEM_ID},
    {"systemsettings", SYSTEM_ID},
    {"hardwaresettings", SYSTEM_ID},
    {"settings", SYSTEM_ID},
    {"advancedsettings", SYSTEM_ID},
    {"filesystem", SYSTEM_ID},
    {"x-enlightenment", SYSTEM_ID},
    {"compiz", SYSTEM_ID},
    {"utility", UTILITIES_ID},
    {"consoleonly", UTILITIES_ID},
    {"pda", UTILITIES_ID},
    {"core", UTILITIES_ID},
    {"favorites", UTILITIES_ID},
    {"pim", UTILITIES_ID},
    {"gpe", UTILITIES_ID},
    {"motif", UTILITIES_ID},
    {"accessibility", UTILITIES_ID},
    {"applet", UTILITIES_ID},
    {"accessories", UTILITIES_ID},
    {"clock", UTILITIES_ID},
    {"calendar", UTILITIES_ID},
    {"calculator", UTILITIES_ID},
    {"documentation", UTILITIES_ID},
    {"archiving", UTILITIES_ID},
    {"compression", UTILITIES_ID},
    {"wine", UTILITIES_ID},
    {"wine-programs-accessories", UTILITIES_ID},
    {"playonlinux", UTILITIES_ID},
    {"filemanager", UTILITIES_ID},
    {"filetools", UTILITIES_ID},
    {"screensaver", UTILITIES_ID},
    {"terminalemulator", UTILITIES_ID},
    {"editors", UTILITIES_ID},
    {"texteditor", UTILITIES_ID},
    {"texttools", UTILITIES_ID},
    {"network", NETWORK_ID},
};

