#!/usr/bin/env python2

# Copyright (c) 2011 ~ 2012 Deepin, Inc.
#               2011 ~ 2012 Liqiang Lee
#
# Author:      Liqiang Lee <liliqiang@linuxdeepin.com>
# Maintainer:  Liqiang Lee <liliqiang@linuxdeepin.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.


from __future__ import print_function
import sys
from ConfigParser import ConfigParser

from facepp import File, API

#API_KEY = '0b8c0488e457432f04e38b79982f66db'
#API_SECRET = 'Bs-ncYt88ewu9euvhBzVo6YjHDzxJpTG'


API_KEY = 'e7d24ca8e91351b8cac02eb6e6080678'
API_SECRET = 'iH_Dls3_gE2wx5dp2cKHPrO8W5V5NTr-'

TARGET_IMAGE = '/tmp/deepin_user_face.png'


from pprint import pformat


def print_result(hint, result):
    def encode(obj):
        if type(obj) is unicode:
            return obj.encode('utf-8')
        if type(obj) is dict:
            return {encode(k): encode(v) for (k, v) in obj.iteritems()}
        if type(obj) is list:
            return [encode(i) for i in obj]
        return obj
    print(hint)
    result = encode(result)
    prefix = '  ' if hint else ''
    print('\n'.join([prefix + i for i in pformat(result, width =
        75).split('\n')]))


api = API(API_KEY, API_SECRET, timeout=10, max_retries=3)

conf = ConfigParser()
with open('/etc/face_recognition.cfg') as f:
    conf.readfp(f)
uuid = conf.get(sys.argv[1], "person_name");

try:
    result = api.detection.detect(img=File(TARGET_IMAGE), mode="oneface")
    face_id = result["face"][0]["face_id"]

    result = api.recognition.verify(person_name=uuid, face_id=face_id)
    print_result("", result)
except Exception, e:
    print(e)
    sys.exit(1)

try:
    print(result['is_same_person'], end='')
except:
    print_result('[Error]: ', result)

